const RECEIVE_TWEETS = 'RECEIVE_TWEETS';
const SET_HASHTAGS = 'SET_HASHTAGS';
const AWAIT_FETCH = 'AWAIT_FETCH';
const START_FETCHING = 'START_FETCHING';

module.exports = {
  RECEIVE_TWEETS,
  SET_HASHTAGS,
  START_FETCHING,
  AWAIT_FETCH
};
